### ISSUE TITLE
TabNine doesn't work with haxe language server

### ISSUE THREAD

**Issue by Getup1** [codota/TabNine#301]
- OS version: Ubuntu 18.04
 - Editor: vim
 - Editor version: 8.0.1453
 - Programming language: Haxe	
 - TabNine extension version: 3.2.20

**Issue Details:**
I have added following lines in my TabNineExample.toml:
```toml
[language.haxe]
command = "haxe"
args = ["--wait", "stdio"]
```
The command `haxe --wait stdio` works normally from shell, but when I'm trying to enable completion from TabNine it says that language server stopped unexpectedly. It keeps saying that after restart.
